version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
