name: CI/CD shape-feature-importer

on:
  push:
    paths:
      - "shape-feature-importer/**"
      - ".github/workflows/ci-shape-feature-importer.yml"
      - "!*.md"

env:
  DB_HOST: ${{ secrets.DB_URL_PROD }}
  DB_USER: ${{ secrets.DB_USER_PROD }}
  DB_NAME: bdp
  PGPASSWORD: ${{ secrets.DB_PWD_PROD }}

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install postgis
        run: sudo apt-get install postgis

      - name: Create geometry table
        run: shp2pgsql -s 4326 ShapefileFeatureImporter/links/LinkStationsGeometries.shp elaboration.bluetoothlinks_tmp | psql -h "${{ env.DB_HOST }}" -U"${{ env.DB_USER }}" "${{ env.DB_NAME }}"

      - name: Update geometries
        run: psql -h "${{ env.DB_HOST }}" -U"${{ env.DB_USER }}" -d "${{ env.DB_NAME }}" -c "set search_path=public,intimev2,elaboration;update edge as e set linegeometry = tmp.geom from ( select s.id,ST_TRANSFORM(ST_LineMerge(t.geom),25832) as geom from elaboration.bluetoothlinks_tmp t join intimev2.station s on t.id=s.id) as tmp where tmp.id=e.edge_data_id;"

      - name: Clean
        run: psql -h "${{ env.DB_HOST }}" -U"${{ env.DB_USER }}" -d "${{ env.DB_NAME }}" -c "drop table elaboration.bluetoothlinks_tmp;"

